export class ChunkUtils {
	static testingchunks = () => {
		return `
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
			BIG ENOUGH TO TRIGGER CHUNKING
		`
	}
}